### ISSUE TITLE
use geojson polygon to query along with district to flexiblly scope up/down the tickets

### ISSUE THREAD

**Issue by ninyawee** [creatorsgarten/bkkchangelog#2]
# now
![image](https://user-images.githubusercontent.com/8089231/222707132-5f230a9e-e8e0-4be4-89fb-3ce9656903da.png)

# expect
able to specify exact area 

# implementation
mongodb already support [geojson query](https://www.mongodb.com/docs/manual/geospatial-queries/)

**Comment by dtinth** [comment]
@wasdee This sounds great! I have already added a `sphere2d` index to the collection:

https://github.com/creatorsgarten/bkkchangelog/blob/220790ba8e8c7bdcc4866d30b0f63b0242faff57/etl/src/index-changelog.ts#L24-L33

However, I have set my MongoDB instance to limit the resource consumption to save costs (max RAM usage 256 MB, and only 800MHz CPU, costs only ฿100/mo. Very hard to find a managed MongoDB service this cheap). However it means that operations on the whole database would be pretty slow. Right now, [a database backup takes 16 minutes](https://github.com/creatorsgarten/bkkchangelog/actions/runs/4303508555) 😂.

Therefore, I need to ensure that EVERY query exposed through the API is fast, that there is no collection scan. I am investigating how geospatial query affects the performance, and for that I need some help:

**Can you provide a few examples GeoJSON data that I can use to test?**

- A small (subdistrict), medium (district), large (region) **Polygon**
- A **MultiPolygon**

**Comment by dtinth** [comment]
@wasdee I have tested, but unfortunately I am unable to make MongoDB use the index efficiently.

**Example:** I search for change log entries within 10 KM of Don Muang airport

```json
  "near": {
    "geometry": {
      "type": "Point",
      "coordinates": [100.5858792,13.7208453]
    },
    "maxDistance": 10000,
    "minDistance": 0
  },
```

<img width="238" alt="image" src="https://user-images.githubusercontent.com/193136/222719643-b51edf27-b81d-467b-a48d-3184740fcba1.png">

It has to examine 9000+ documents, taking **24 ms** to query.

## Proposed alternative

I plan to allow specifying multiple districts in a single query like this:

```json
  "district": ["บางเขน","ดอนเมือง","สายไหม","หลักสี่"]
```

Here the index is more efficiently used, resulting in 150x less documents examined, taking **0 ms** to query.

<img width="261" alt="image" src="https://user-images.githubusercontent.com/193136/222719985-36bfda70-7722-41a1-b9dc-8a1e8116758e.png">

**Comment by ninyawee** [comment]
i see. interesting

# thoughts
There is 236533 tickers, I think the db perform KDTree search which is quite optimal.
if we don't pay for the bandwidth then let send the whole things and let client filter out on their side.

I'm not sure why 24ms is that of an issue. are we want to make db immortal to abuse? are we having >1000req/s?
anyway, I'm totally ok with all. I love multi-district idea a lot. 

# adding to your alternative
we could easily incorporate smaller-area to further scope down as well. but perhaps [KISS](https://en.wikipedia.org/wiki/KISS_principle) is the way to go now.

# my proposed alternative
There is [h3](https://github.com/uber/h3). we could perform prefix string match instead. we need to pre-compute all the coord to h3 index first. the similar idea to district, but more uniform and predictable. not exact match, but pretty good approx.
see https://observablehq.com/@nrabinowitz/h3-indexing-order

**Comment by dtinth** [comment]
@wasdee

> let send the whole things and let client filter out on their side

[That took 16 minutes.](https://github.com/creatorsgarten/bkkchangelog/actions/runs/4303508555)

> I'm not sure why 24ms is that of an issue. are we want to make db immortal to abuse? are we having >1000req/s?

- I don’t want to add an API and later remove it due to it causing performance problems. Right now all the queries that are made available via the API has very predictable performance. The API always returns max 64 results and every query is optimized so that no more than ~100 document scan per query. You can think of it as almost __O(1)__[^1].

   - This helps keep the system architecture simple because **no caching layer is needed** since the performance is so predictable. We can get by by having every query query the database directly. 

- I want to encourage people to just download the database dump and play with it (for more advanced use cases).

   - Are there any places where we can send this as a public dataset where it can be queried more expressively? That might be a good idea for a userland project. I have seen some people use Tableau, Metabase, Elastic, etc. to do data analysis but I don’t have much experience.

[^1]: it’s more like O(log n) tho

**Comment by dtinth** [comment]
I just checked H3, thanks for sharing! Because it is a prefix search rather than an exact match (like a district), it cannot be easily indexed in a way that provides constant query time while allowing for chronological sorting.

Meanwhile, support for multiple districts has been added. The swagger UI cannot display it but it’s now specified in the OpenAPI spec. Also the `explain` parameter is added to return the query performance info.
